# Generated by Django 3.1.7 on 2021-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unsplash_collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='unsplash_colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='unsplash_conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='unsplash_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='unsplash_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_primary_landmark_confidence', models.CharField(max_length=255)),
                ('tagged', models.BooleanField(default=False)),
            ],
        ),
    ]
