# Generated by Django 3.1.7 on 2021-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsplash_collections',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unsplash_colors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unsplash_conversions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unsplash_keywords',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='id',
        ),
        migrations.AddField(
            model_name='unsplash_collections',
            name='collection_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_collections',
            name='photo_collected_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_collections',
            name='photo_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='ai_coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='blue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='green',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='hex',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='photo_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unsplash_colors',
            name='red',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_conversions',
            name='anonymous_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_conversions',
            name='conversion_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_conversions',
            name='converted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_conversions',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_conversions',
            name='photo_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unsplash_keywords',
            name='ai_service_1_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_keywords',
            name='ai_service_2_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_keywords',
            name='photo_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unsplash_keywords',
            name='suggested_by_user',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='ai_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_aperture_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_camera_make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_camera_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_exposure_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_focal_length',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='exif_iso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_aspect_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_location_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_location_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_location_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_location_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photo_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photographer_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photographer_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='photographer_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='stats_downloads',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unsplash_photos',
            name='stats_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_collections',
            name='collection_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_colors',
            name='ai_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_conversions',
            name='conversion_country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_keywords',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_confidence',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
