# Generated by Django 3.1.7 on 2021-02-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20210220_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unsplash_collections',
        ),
        migrations.DeleteModel(
            name='unsplash_colors',
        ),
        migrations.DeleteModel(
            name='unsplash_conversions',
        ),
        migrations.DeleteModel(
            name='unsplash_keywords',
        ),
    ]
