# Generated by Django 3.1.7 on 2021-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20210220_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
