# Generated by Django 3.1.7 on 2021-02-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20210220_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='ai_description',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_confidence',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_latitude',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_longitude',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='ai_primary_landmark_name',
        ),
    ]
