# Generated by Django 3.1.7 on 2021-02-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20210220_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_iso',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photo_location_latitude',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photo_location_longitude',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photo_submitted_at',
        ),
    ]
