# Generated by Django 3.1.7 on 2021-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20210220_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsplash_photos',
            name='photo_description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
