# Generated by Django 3.1.7 on 2021-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20210220_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_aperture_value',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_camera_make',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_camera_model',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_exposure_time',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='exif_focal_length',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photo_featured',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photo_location_name',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='photographer_username',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='stats_downloads',
        ),
        migrations.RemoveField(
            model_name='unsplash_photos',
            name='stats_views',
        ),
    ]
